language: python
python:
  - '2.7'
  - '3.4'
  - '3.5-dev'
  - '3.8'
  - 'nightly'
matrix:
  allow_failures:
    - python: 'nightly'
before_install:
  - pip install pep8
script:
  - pep8 --max-line-length=120 .
  - python -m unittest discover
